'use client'

import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

export default function AuthPage() {
  const router = useRouter(); const [mode, setMode] = useState<'signin'|'signup'>('signin'); const [role, setRole] = useState<'tenant'|'landlord'>('tenant'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [name, setName] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setMessage(''); const supabase = createClient(); const result = mode === 'signin' ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password, options: { emailRedirectTo: process.env.NEXT_PUBLIC_DEV_SUPABASE_REDIRECT_URL ?? `${window.location.origin}/auth/callback`, data: { full_name: name, role } } }); setLoading(false); if (result.error) { setMessage(result.error.message.includes('Invalid') ? 'Invalid email or password.' : result.error.message); return } if (mode === 'signup') { setMessage('Check your email to confirm your account, then sign in.'); setMode('signin'); return } router.push('/dashboard') }
  return <main className="min-h-screen bg-[#f6f9fc] px-6 py-10 text-[#1B2A4A]"><div className="mx-auto grid max-w-5xl overflow-hidden rounded-3xl bg-white shadow-xl lg:grid-cols-2"><section className="bg-[#1B2A4A] p-10 text-white lg:p-14"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-emerald-300">VerifiedRent Ghana</p><h1 className="mt-20 text-4xl font-bold leading-tight">Rent with more confidence.</h1><p className="mt-5 max-w-sm text-slate-300">Secure accounts, verified landlords, and trusted homes across Ghana.</p></section><section className="p-8 lg:p-14"><div className="mb-8 flex gap-2 rounded-xl bg-slate-100 p-1"><button onClick={() => setMode('signin')} className={`flex-1 rounded-lg px-4 py-2 text-sm font-semibold ${mode === 'signin' ? 'bg-white shadow' : 'text-slate-500'}`}>Sign in</button><button onClick={() => setMode('signup')} className={`flex-1 rounded-lg px-4 py-2 text-sm font-semibold ${mode === 'signup' ? 'bg-white shadow' : 'text-slate-500'}`}>Create account</button></div><h2 className="text-3xl font-bold">{mode === 'signin' ? 'Welcome back' : 'Create your account'}</h2><p className="mt-2 text-slate-500">{mode === 'signin' ? 'Access your rental workspace.' : 'Choose how you will use VerifiedRent.'}</p><form onSubmit={submit} className="mt-8 flex flex-col gap-4">{mode === 'signup' && <input required value={name} onChange={e => setName(e.target.value)} placeholder="Full name" className="rounded-xl border px-4 py-3 outline-none focus:border-emerald-500" />}{mode === 'signup' && <div className="grid grid-cols-2 gap-2">{(['tenant','landlord'] as const).map(item => <button type="button" key={item} onClick={() => setRole(item)} className={`rounded-xl border px-4 py-3 capitalize ${role === item ? 'border-emerald-500 bg-emerald-50 text-emerald-700' : ''}`}>{item}</button>)}</div>}<input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="Email address" className="rounded-xl border px-4 py-3 outline-none focus:border-emerald-500" /><input required minLength={6} type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Password" className="rounded-xl border px-4 py-3 outline-none focus:border-emerald-500" /><button disabled={loading} className="rounded-xl bg-emerald-500 px-4 py-3 font-semibold text-white hover:bg-emerald-600 disabled:opacity-60">{loading ? 'Please wait…' : mode === 'signin' ? 'Sign in securely' : 'Create account'}</button>{message && <p className="rounded-xl bg-slate-100 p-3 text-sm text-slate-600">{message}</p>}</form></section></div></main>
}
