'use client'

import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type Props = { adminId: string; applications: any[]; reports: any[]; listings: any[]; audit: any[] }
export function AdminDashboard({ adminId, applications, reports, listings, audit }: Props) {
  const supabase = createClient(); const [notice, setNotice] = useState('')
  async function review(application: any, status: 'approved' | 'rejected') {
    const reason = status === 'rejected' ? window.prompt('Reason for rejection')?.trim() || 'Your verification application was rejected.' : ''
    setNotice('Saving review…')
    const { error } = await supabase.from('verification_applications').update({ status, reviewed_at: new Date().toISOString(), ...(status === 'rejected' ? { rejection_reason: reason } : { rejection_reason: null }) }).eq('id', application.id)
    if (!error && status === 'approved') {
      await supabase.from('landlord_profiles').update({ verification_status: 'approved' }).eq('user_id', application.landlord_id)
      await supabase.from('properties').update({ is_verified_landlord: true }).eq('landlord_id', application.landlord_id)
    }
    await supabase.from('notifications').insert({ user_id: application.landlord_id, type: status === 'approved' ? 'verification_approved' : 'verification_rejected', title: status === 'approved' ? 'Verification approved' : 'Verification rejected', message: status === 'approved' ? 'Your landlord verification has been approved.' : reason, is_read: false, related_entity_id: application.id })
    await supabase.from('admin_audit_logs').insert({ admin_id: adminId, action: status === 'approved' ? 'approve_verification' : 'reject_verification', entity_type: 'verification_application', entity_id: application.id })
    setNotice(error ? 'Could not save the review.' : 'Review saved.'); if (!error) window.location.reload()
  }
  async function updateReport(report: any, status: string) { await supabase.from('fraud_reports').update({ status }).eq('id', report.id); await supabase.from('admin_audit_logs').insert({ admin_id: adminId, action: `report_${status}`, entity_type: 'fraud_report', entity_id: report.id }); window.location.reload() }
  return <main className="min-h-screen bg-[#f7fafc] px-6 py-10 text-[#1B2A4A]"><div className="mx-auto max-w-7xl"><header className="mb-8 flex items-end justify-between"><div><a href="/" className="flex items-center gap-3 text-[#1B2A4A]"><img loading="lazy" src="/verifiedrent-logo.webp" alt="VerifiedRent Ghana logo" className="size-10 object-contain" /><span className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-600">VerifiedRent Ghana</span></a><h1 className="mt-2 text-3xl font-black">Admin dashboard</h1></div><a href="/dashboard" className="rounded-xl border bg-white px-4 py-2 text-sm font-bold">Back to dashboard</a></header>{notice && <p role="status" className="mb-4 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{notice}</p>}<div className="grid gap-5 md:grid-cols-4"><Stat label="Verification queue" value={applications.filter(a => a.status === 'submitted').length} /><Stat label="Open reports" value={reports.filter(r => r.status !== 'resolved').length} /><Stat label="Listings" value={listings.length} /><Stat label="Audit actions" value={audit.length} /></div><section className="mt-8 rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Verification applications</h2><div className="mt-4 divide-y">{applications.map(a => <div key={a.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><p className="font-bold">{a.legal_name}</p><p className="text-sm text-slate-500">{a.status} · {new Date(a.created_at).toLocaleDateString()}</p></div><div className="flex gap-2"><button onClick={() => review(a, 'approved')} className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-bold text-white">Approve</button><button onClick={() => review(a, 'rejected')} className="rounded-lg border border-red-200 px-3 py-2 text-sm font-bold text-red-700">Reject</button></div></div>)}</div></section><section className="mt-8 rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Fraud reports</h2><div className="mt-4 divide-y">{reports.map(r => <div key={r.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><p className="font-bold">{r.category}</p><p className="text-sm text-slate-500">{r.details || 'No details provided'} · {r.status || 'open'}</p></div><button onClick={() => updateReport(r, 'resolved')} className="rounded-lg bg-[#1B2A4A] px-3 py-2 text-sm font-bold text-white">Mark resolved</button></div>)}</div></section><section className="mt-8 rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Recent audit log</h2><div className="mt-4 divide-y">{audit.slice(0, 10).map(item => <p key={item.id} className="py-3 text-sm"><strong>{item.action}</strong> · {item.entity_type} · {new Date(item.created_at).toLocaleString()}</p>)}</div></section></div></main>
}
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div> }
