'use client'

import { useState, type ChangeEvent, type FormEvent, type ReactNode } from 'react'
import { createClient } from '@/lib/supabase/client'

const propertyTypes = ['Apartment', 'Single Room', 'Self-Contained', 'House', 'Compound House', 'Airbnb', 'Hotel', 'Guesthouse', 'Office Space', 'Land', 'Warehouse']
type Lookup = { id: string; name: string }
type District = { id: number; name: string; capital_city: string | null }
type Listing = { id: string; title: string; property_type: string; price: number; status: string }
type Metric = { views: number; likes: number; inquiries: number }

export function LandlordFeed({ userId, properties, regions, analyticsByType = {} }: { userId: string; properties: Listing[]; regions: Lookup[]; analyticsByType?: Record<string, Metric> }) {
  const supabase = createClient()
  const [form, setForm] = useState({ title: '', description: '', property_type: 'Apartment', region_id: '', district_id: '', price: '' })
  const [districts, setDistricts] = useState<District[]>([])
  const [photos, setPhotos] = useState<File[]>([])
  const [notice, setNotice] = useState('')
  const [busy, setBusy] = useState(false)
  const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }))
  async function chooseRegion(region_id: string) { setForm((current) => ({ ...current, region_id, district_id: '' })); const { data } = await supabase.from('districts').select('id,name,capital_city').eq('region_id', region_id).order('name'); setDistricts(data ?? []) }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setNotice('')
    const { data: property, error } = await supabase.from('properties').insert({ landlord_id: userId, title: form.title.trim(), description: form.description.trim(), price: Number(form.price), location: districts.find((item) => String(item.id) === form.district_id)?.name ?? '', region_id: form.region_id, district_id: Number(form.district_id), property_type: form.property_type, status: 'published' }).select('id').single()
    if (error || !property) { setNotice('We could not publish this listing. Please check the form.'); setBusy(false); return }
    const rows: { property_id: string; image_url: string; is_cover: boolean }[] = []
    for (const [index, photo] of photos.slice(0, 8).entries()) { const path = `${userId}/${property.id}/${crypto.randomUUID()}-${photo.name.replace(/[^a-zA-Z0-9._-]/g, '-')}`; const upload = await supabase.storage.from('property-images').upload(path, photo, { contentType: photo.type }); if (!upload.error) { const { data: url } = supabase.storage.from('property-images').getPublicUrl(path); rows.push({ property_id: property.id, image_url: url.publicUrl, is_cover: index === 0 }) } }
    if (rows.length) await supabase.from('property_images').insert(rows)
    setNotice('Your first listing is live. Tenants can find it now.'); setForm({ title: '', description: '', property_type: 'Apartment', region_id: '', district_id: '', price: '' }); setDistricts([]); setPhotos([]); setBusy(false)
  }
  return <section className="space-y-6"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-emerald-600">Your first listing</p><h2 className="mt-2 text-3xl font-black">Sign up. Post. Go live.</h2><p className="mt-2 text-slate-500">No verification, payment, ID, or camera is needed. Add up to 8 photos, choose the exact district, and publish your property in one guided step.</p></div><form onSubmit={submit} className="grid gap-4 rounded-3xl border border-slate-200 bg-white p-6 sm:grid-cols-2"><Field label="Title" required value={form.title} onChange={(e: ChangeEvent<HTMLInputElement>) => set('title', e.target.value)} /><Field label="Property type" as="select" value={form.property_type} onChange={(e: ChangeEvent<HTMLSelectElement>) => set('property_type', e.target.value)}>{propertyTypes.map((item) => <option key={item}>{item}</option>)}</Field><Field label="Region" as="select" required value={form.region_id} onChange={(e: ChangeEvent<HTMLSelectElement>) => chooseRegion(e.target.value)}><option value="">Choose region</option>{regions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Field><Field label="District" as="select" required value={form.district_id} disabled={!form.region_id} onChange={(e: ChangeEvent<HTMLSelectElement>) => set('district_id', e.target.value)}><option value="">Choose district</option>{districts.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.capital_city}</option>)}</Field><Field label="Price (GHS)" type="number" min="0" required value={form.price} onChange={(e: ChangeEvent<HTMLInputElement>) => set('price', e.target.value)} /><label className="text-sm font-semibold text-slate-700">Photos <span className="font-normal text-slate-500">(up to 8; first is cover)</span><input className="mt-2 block w-full rounded-xl border border-slate-200 p-3 text-sm" type="file" accept="image/*" multiple required={properties.length === 0} onChange={(e) => setPhotos(Array.from(e.target.files ?? []).slice(0, 8))} /></label><label className="sm:col-span-2 text-sm font-semibold text-slate-700">Description<textarea required value={form.description} onChange={(e) => set('description', e.target.value)} className="mt-2 min-h-32 w-full rounded-xl border border-slate-200 p-3 font-normal outline-none focus:border-emerald-500" /></label><button disabled={busy} className="sm:col-span-2 rounded-xl bg-[#10233d] px-5 py-3 font-bold text-white disabled:opacity-50">{busy ? 'Publishing…' : 'Publish property'}</button>{notice && <p className="sm:col-span-2 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{notice}</p>}</form><div className="grid gap-3 sm:grid-cols-3">{Object.entries(analyticsByType).map(([type, metric]) => <div key={type} className="rounded-2xl border border-slate-200 bg-white p-4"><p className="font-bold">{type}</p><p className="mt-2 text-sm text-slate-500">{metric.views} views · {metric.likes} likes · {metric.inquiries} inquiries</p></div>)}</div></section>
}
function Field({ label, as = 'input', children, ...props }: { label: string; as?: 'input' | 'select'; children?: ReactNode; [key: string]: any }) { const Component = as; return <label className="text-sm font-semibold text-slate-700">{label}<Component {...props} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-3 font-normal outline-none focus:border-emerald-500">{children}</Component></label> }
